"""
------------------------------------------------------------------------------
Copyright 2023 Matthew Pope

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
------------------------------------------------------------------------------


Misc utilities.
"""

from datetime import datetime


def season_id_to_int(season_id):
    """
    Util to convert a season_id to an int.
    """
    return int(season_id[:4])


def get_rowset_mapping(result_sets, column_names):
    """
    Returns a list of mapped fields to the passed headers.
    """

    headers = result_sets['headers']
    mapped = {}
    for column in column_names:
        column_upper = column.upper()
        if column_upper not in headers:
            mapped[column] = None
        else:
            mapped[column] = headers.index(column.upper())

    return mapped


def column_names_from_table(db, table_name):
    """
    Gets the column names from a db table.
    """

    columns = db.get_columns(table_name)
    mapped = [column.name for column in columns]

    # season_id is our construct, and isn't returned by any NBA endpoint.
    if 'season_id' in mapped:
        mapped.remove('season_id')

    # Ignore autogenerated id columns.
    if 'id' in mapped:
        mapped.remove('id')

    return mapped


def chunk_list(in_list, n):
    """
    Chunk list into lists of length n.
    """
    return [in_list[i:i + n] for i in range(0, len(in_list), n)]


def progress_bar(iterable, prefix='', suffix='', decimals=1, length=100, fill='█', printEnd="\r", quiet=False):
    """
    https://stackoverflow.com/questions/3173320/text-progress-bar-in-the-console
    Call in a loop to create terminal progress bar
    @params:
    iteration   - Required  : current iteration (Int)
    total       - Required  : total iterations (Int)
    prefix      - Optional  : prefix string (Str)
    suffix      - Optional  : suffix string (Str)
    decimals    - Optional  : number of decimals in percent complete (Int)
    length      - Optional  : character length of bar (Int)
    fill        - Optional  : bar fill character (Str)
    printEnd    - Optional  : end character (e.g. "\r", "\r\n") (Str)
    quiet       - Optoinal  : should do printing. (Bool)
    """
    total = 1
    if iterable:
        total = len(iterable)

    # Progress Bar Printing Function
    def printProgressBar(iteration):
        percent = (
            ("{0:." + str(decimals) + "f}")
            .format(100 * (iteration / float(total)))
        )
        filledLength = int(length * iteration // total)
        bar = fill * filledLength + '-' * (length - filledLength)
        if not quiet:
            print(f'\r{prefix} |{bar}| {percent}% {suffix}', end=printEnd)
    # Initial Call
    printProgressBar(0)
    # Update Progress Bar
    for i, item in enumerate(iterable):
        yield item
        printProgressBar(i + 1)
    # Print New Line on Complete
    if not quiet:
        print()


def generate_valid_seasons():
    """
    Genrate the valid seasons to choose from, starting at 1997 to the current season.
    This assumes that a season begins in October.
    """

    valid_seasons = []
    if datetime.now().month > 10:
        curr_season = datetime.now().year - 2000 + 1
    else:
        curr_season = datetime.now().year - 2000
    for x in range(1997, curr_season + 2000):
        valid_season = generate_valid_season(x)
        valid_seasons.append(valid_season)

    return valid_seasons


def generate_valid_season(season):
    # Create string, reverse
    tmp = f"{(season % 100 + 1):02d}"[::-1]

    # Get last two vals of the last string, due to 1999's next season being 100
    next_year_rev = tmp[0:2]

    # re-reverse.
    next_year = next_year_rev[::-1]
    return f"{season}-{next_year}"
